BEGIN TRANSACTION;
CREATE TABLE `userAccounts` (
	`pk`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`uuid`	TEXT NOT NULL UNIQUE,
	`project`	INTEGER NOT NULL,
	`username`	TEXT NOT NULL,
	`password`	TEXT NOT NULL
);
CREATE TABLE "projects" (
	`pk`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`uuid`	INTEGER NOT NULL UNIQUE,
	`projectname`	TEXT NOT NULL UNIQUE
);
CREATE TABLE "authtokens" (
	`pk`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`id`	INTEGER NOT NULL,
	`token`	INTEGER NOT NULL,
	`expiry`	INTEGER
);
CREATE TABLE "adminKey" (
	`pk`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`id`	INTEGER NOT NULL,
	`project`	INTEGER NOT NULL
);
CREATE TABLE "adminAccounts" (
	`pk`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`uuid`	TEXT NOT NULL,
	`username`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);
COMMIT;
